apiVersion: v1
kind: Pod
metadata:
  name: my-pod-2
spec:
  containers:
  - name: nginx
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - name: mysecret-volume
      mountPath: /etc/mysecret
      readOnly: true
  volumes:
  - name: mysecret-volume
    secret:
      secretName: mysecret
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
    env:
    - name: DB_USERNAME
      valueFrom:
        configMapKeyRef:
          name: myconfigmap
          key: username
    - name: DB_PASSWORD
      valueFrom:
        configMapKeyRef:
          name: myconfigmap
          key: password
  volumes:
  - name: config-volume
    configMap:
      name: myconfigmap
